// Catalogue d'activités sensorielles (base courte, extensible)
export const CATEGORIES = ['Olfactif', 'Tactile', 'Auditif', 'Proprioception', 'Calme'];

export default [
  {
    id: 'sniff_tapis',
    title: 'Tapis de fouille',
    category: 'Olfactif',
    level: 'Débutant',
    durationMin: 5,
    materials: ['Tapis de fouille', 'Croquettes / friandises'],
    steps: [
      'Prépare 10–15 friandises.',
      'Cache-les dans le tapis, à différentes profondeurs.',
      'Laisse le chien chercher sans aide (observe).',
      'Augmente peu à peu la difficulté.',
    ],
    safety: 'Surveille l’ingestion de tissu. Retire si le chien mâchouille le tapis.',
    goal: 'Fatigue mentale douce via le flair.',
  },
  {
    id: 'sniff_boites',
    title: 'Jeu des boîtes',
    category: 'Olfactif',
    level: 'Équilibré',
    durationMin: 8,
    materials: ['3–5 boîtes/cartons', 'Friandises'],
    steps: [
      'Place les boîtes au sol, ouvertes.',
      'Cache des friandises dans 1–2 boîtes.',
      'Laisse le chien explorer, ne pas indiquer tout de suite.',
      'Augmente le nombre de boîtes / change l’emplacement.',
    ],
    safety: 'Évite les agrafes, scotchs coupants. Pas de frustration prolongée.',
    goal: 'Affiner l’exploration olfactive + autonomie.',
  },
  {
    id: 'tactile_textures',
    title: 'Parcours textures',
    category: 'Tactile',
    level: 'Débutant',
    durationMin: 6,
    materials: ['Tapis, serviette, carton, paillasson'],
    steps: [
      'Dispose 3–4 textures au sol en chemin.',
      'Invites-y le chien librement, récompense chaque contact.',
      'Alterne vitesse/arrêts, laisse renifler.',
    ],
    safety: 'Antidérapant. Pas de surfaces tranchantes/chaudes.',
    goal: 'Confiance et conscience corporelle douce.',
  },
  {
    id: 'auditif_douceur',
    title: 'Sons doux + mâchouillage',
    category: 'Auditif',
    level: 'Débutant',
    durationMin: 10,
    materials: ['Jouet à mâcher', 'Playlist relax (faible)'],
    steps: [
      'Lance une playlist calme (volume bas).',
      'Propose un jouet à mâcher en parallèle.',
      'Observe respiration / tension / pauses.',
    ],
    safety: 'Volume très bas. Si stress → stop immédiat.',
    goal: 'Association positive sons calmes + auto-apaisement.',
  },
  {
    id: 'proprio_coussins',
    title: 'Coussins instables',
    category: 'Proprioception',
    level: 'Équilibré',
    durationMin: 7,
    materials: ['2–3 coussins/plaids', 'Friandises'],
    steps: [
      'Empile 2 coussins pour créer une légère instabilité.',
      'Le chien monte, tu récompenses chaque appui stable.',
      'Courtes pauses, 3–4 répétitions.',
    ],
    safety: 'Toujours au sol, pas de hauteur. Arrêter si tremblements/stress.',
    goal: 'Renforcer muscles profonds + équilibre.',
  },
  {
    id: 'calme_lickmat',
    title: 'Lick mat (léchage calme)',
    category: 'Calme',
    level: 'Débutant',
    durationMin: 10,
    materials: ['Tapis à lécher', 'Pâtée adaptée / yaourt chien'],
    steps: [
      'Étale fine couche sur le tapis.',
      'Pose au sol, pas d’interruption.',
      'Retire avant saturation (laisse sur une note positive).',
    ],
    safety: 'Vérifie la tolérance digestive. Hygiène du tapis.',
    goal: 'Auto-apaisement par léchage, favoriser la détente.',
  },
];
